on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-with:
    name: Default (with)
    runs-on: ubuntu-latest
    steps:
      - name: "Get: WITH"
        id: node_release_with
        uses: rez0n/actions-github-release@main
        with:
          repository: "nodejs/node"
          type: "stable"

      - name: "Echo: WITH"
        env:
          VERSION: ${{ steps.node_release_with.outputs.release }}
        run: echo "Release ${VERSION}"

  test-env:
    name: Default (env)
    runs-on: ubuntu-latest
    steps:
      - name: "Get: ENV"
        id: node_release_env
        uses: rez0n/actions-github-release@main
        env:
          repository: "nodejs/node"
          type: "stable"
      
      - name: "Echo: ENV"
        env:
          VERSION: ${{ steps.node_release_env.outputs.release }}
        run: echo "Release ${VERSION}"

  test-regex:
    name: ENV + regex
    runs-on: ubuntu-latest
    steps:
      - name: "Get: ENV + regex"
        id: node_release_env
        uses: rez0n/actions-github-release@main
        env:
          repository: "nodejs/node"
          type: "stable"
          filter: '^.*(?<!^v24\.15\.0$)$'
      
      - name: "Echo: - ENV + regex"
        env:
          VERSION: ${{ steps.node_release_env.outputs.release }}
        run: echo "Release ${VERSION}"
